# Generated by Django 2.1.7 on 2019-03-23 13:14

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default='Content', verbose_name='Content'),
            preserve_default=False,
        ),
    ]
