# Generated by Django 2.1.7 on 2019-03-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default=True, upload_to=''),
            preserve_default=False,
        ),
    ]
