# Generated by Django 2.1.7 on 2019-03-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='chapitre',
            field=models.TextField(default='chapite'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
