# Generated by Django 2.1.7 on 2019-03-26 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evenements', '0003_auto_20190326_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='moderators',
        ),
        migrations.AddField(
            model_name='event',
            name='moderators',
            field=models.ManyToManyField(to='evenements.Moderator'),
        ),
        migrations.RemoveField(
            model_name='moderator',
            name='user',
        ),
        migrations.AddField(
            model_name='moderator',
            name='user',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
